appName: hello-api

namespace: dev

replicaCount: 3

image:
  repository: bharat777/hello-api
  tag: 7622221d562ddb4c764c11913f96e6ffed4c38b7

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"

  limits:
    memory: "256Mi"
    cpu: "200m"