appName: hello-api

namespace: dev

replicaCount: 3

image:
  repository: bharat777/hello-api
  tag: 48f6a983c66eab3af752935ad4f974a0382600c2

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"

  limits:
    memory: "256Mi"
    cpu: "200m"