name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

      imageTag:
        description: "Docker image tag"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Setup Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy using Helm
        run: |
          helm upgrade --install hello-api ./hello-api-chart \
            -n ${{ github.event.inputs.environment }} \
            -f environments/${{ github.event.inputs.environment }}-values.yaml \
            --set image.tag=${{ github.event.inputs.imageTag }} \
            --atomic --timeout 5m